description: |
  Base image for this Orb.
  This Orb depends on curl and jq, so please install them when you use other images.

parameters:
  tag:
    type: string
    default: stable
    description: >
      Pick a specific cimg/base image variant:
      https://hub.docker.com/r/cimg/base/tags

docker:
  - image: 'cimg/base:<< parameters.tag >>'
